### ISSUE TITLE
Signer social proofs

### ISSUE THREAD

**Issue by radicleart** [Stacks-Builders/sbtc-bridge-api#40]
Framework for signers to link real world identities to public keys via social proofs.

See [GitBook](https://brighton-blockchain.gitbook.io/sbtc-bridge/sbtc-bridge-plan/signer-social-proofs) for details

**Comment by friedger** [comment]
Did:web could be the easiest solution

**Comment by radicleart** [comment]
@friedger thanks - am reading [w3c did web spec](https://w3c-ccg.github.io/did-method-web/)

do you know any other useful refs ?

**Comment by jo-tm** [comment]
Interesting! The W3C DID Web spec could be a useful solution. It utilizes a web domain's reputation to establish social proofs and link real-world identities to signing keys. This could address some challenges and potentially drive adoption. Worth exploring further...

**Comment by jo-tm** [comment]
There an Improvement Proposal for Ethereum that is peer-reviewed now, for Signing with Blockchain Wallet:

https://eips.ethereum.org/EIPS/eip-4361
